title: Molino
url: "https://molino.digital"
baseurl: ""
markdown: kramdown
theme: minima
collections:
  projects:
    output: true
    permalink: /projects/:name/
  blog:
    output: true
    permalink: /projects/:blog/	
header_pages:
  - projects.md
  - about.md
  - contact.md
