title: Molino
url: "https://molino.digital"
baseurl: ""
markdown: kramdown
theme: minima
minima: 
  nav_pages:
    - projects.md
    - about.md
    - contact.md
collections:
  projects:
    output: true
    permalink: /projects/:name/
