title: Molino
url: "https://molino.digital"
baseurl: ""
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /projects/:name/
header_pages:
  - projects.md
  - about.md
  - contact.md
